version: '3.8'

services:
  db:
    image: mariadb:10.11
    container_name: mastermind_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mastermind
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mastermind_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=mastermind
      - SECRET_KEY=sua_chave_secreta_jwt_jwt_12345
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mastermind_frontend
    restart: always
    ports:
      - "8080:80" # Mapeia a porta 80 do Nginx interno para 8080 no host
    depends_on:
      - backend

volumes:
  db_data:
