FROM python:3.10-slim

WORKDIR /app

# Instalar dependências base do sistema operacional que podem ser necessárias para builds em C (ex: bcrypt)
RUN apt-get update && apt-get install -y \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
